#!/bin/bash
# SPDX-License-Identifier: MIT
# Copyright (c) 2023 Gene C
#
# installer script for iwinfo
# e.g. Call from PKGBUILD:  
#   ./do-install ${pkgdir}
# gene c
#
dest="$1"
self='iwinfo'

Docs="Docs"
info="README.rst scripts packaging"
infodir="/usr/share/${self}"

license="Docs/License.rst"
licensedir="/usr/share/licenses/${self}"

etc='/etc/iwinfo/'
confs='etc/wifi.db.sample'

# list apps without the ".py" or leave empty string
libexec=('iwinfo.py')
apps_sdir='src/ambient'
apps=('iwinfo')

# so can make app link in /usr/bin
sitedir=$(/usr/bin/python3 -c "import site; print(site.getsitepackages()[0])")
self_sitedir=${sitedir}/${self//-/_}

if [ ! -d "$dest" ] ; then
    echo 'Missing destination directory'
    exit 1
else
    # shared
    /usr/bin/rsync --mkpath -a ${Docs} ${dest}/${infodir}/
    /usr/bin/rsync --mkpath -a ${info} ${dest}${infodir}
    /usr/bin/rsync --mkpath -a ${license} ${dest}/${licensedir}/

    # /etc/iwinfo must be readable by non-priv user
    mkdir -p ${dest}/${etc}
    chmod 755 ${dest}/${etc}
    /usr/bin/rsync -a --mkpath ${confs} ${dest}/${etc}/

    /usr/bin/python -m installer --destdir="$dest" dist/*.whl

    # link(s) in /usr/lib/${self}/
    if [ -v libexec ] ; then
        /usr/bin/mkdir -p "${dest}/usr/lib/${self}"
        for app in ${libexec[@]}
        do
            /usr/bin/ln -sf ${self_sitedir}/${app} ${dest}/usr/lib/${self}/${app}
        done
    fi
    if [ -v apps ] ; then
        for app in ${apps[@]}
        do
            rsync -a --mkpath ${apps_sdir}/$app ${dest}/usr/bin/$app
            chmod 655 ${dest}/usr/bin/$app
        done
    fi

    exit 0
fi

