#!/bin/bash
# SPDX-License-Identifier: MIT
# Copyright (c) 2023 Gene C
#
# installer script for iwinfo
#   ./do-install ${destination-directory}
#

if (( $# < 1 )) ; then
    dest='build/pkg'
else
    dest="$1"
fi

dest=$(realpath "$dest")

/usr/bin/meson install -C build/release --destdir "$dest" > /dev/null

exit 0

